### ISSUE TITLE
On BC dates and Anno Domini

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/ImperatorToCK3#106]
A further conversion option should be added for people who may wish to convert their I:R game to the Gregorian calendar without teleporting people centuries after their birth.

The oldest ever used date in I:R files is 320 AVC (433 BCE) and CK3 cannot handle negative dates in any way. (Not counting Zoroaster, who is given a lifespan of 1-60 AVC/754-693 BC, but never ruled)

Hence, it is warned that users do _not_ select this option unless they're converting saves from after 803 AVC/50 AD.

How will it do its job:
- For any I:R date, check if the year value is lower or equal to 760
  - If YES: set the following variables:
    - A: I:R year minus 303
    - B: floor of {A divided by 100}
    - C: A modulo 100
    - D: floor of {C divided by 10}
    - E: C modulo 10
    - ... and then set the new I:R date to be {B+1}.{C+1}.{D+1} (yy.mm.dd.)
  - If NO: set the new I:R date to be {I:R year minus 753}.{I:R month}.{I:R day}

In this way, all rulers would appear in the correct succession, albeit they would never be aged more than mere months. This is useful only for the purpose of regnal numbers (i.e. having an Alexander V as Macedonia and not an Alexander I).

A further file, called _prehistory.txt_ will need to be added to supply historical leaders that have died before I:R game start (and are thus not recorded in the savegame anyway): [prehistory.txt](https://github.com/ParadoxGameConverters/ImperatorToCK3/files/5696902/prehistory.txt)

**Comment by IohannesIohannium** [comment]
Superseeded by less complicated suggestion #250

**Comment by IhateTrains** [comment]
I think the prehistory.txt part is still relevant, I don't see other options for handling the issue.

**Comment by IhateTrains** [comment]
Or do I?
```

			historical_regnal_numbers={
				Agis=3
				Archidamos=3
				Kleomenes=2
				Kleombrotos=1
				Agesipolis=2
				Pausanias=1
				Pleistarchos=1
				Leonidas=1
				Polydoros=1
				Menelaos=1
				Orestes=1
				Dion=1
				Aristodemos=1
				Demaratos=1
			}
```
Country entries in saves have this bloc, we could use it to generate pre-Imperator ruler characters. They'd totally lack uniqueness, but who cares if we can't give them real ruler term dates anyway.

**Comment by IohannesIohannium** [comment]
Well, it works well enough like this
