### ISSUE TITLE
Vanishing titles

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#119]
Iohannes' report: 
>there is (and it was already here) a bug that makes some of these titles "vanish". E.g. Ptolemy the Liberator is scheduled to gain k_egypt, but instead he is reduced to a count. I have no idea why this happens. It is not the order of the file, as Chandragupta, with the same format, keeps his e_india.

**Comment by IhateTrains** [comment]
@IohannesIohannium Was the save made on Imperator start?

**Comment by IohannesIohannium** [comment]
Yes, before unpausing.

**Comment by IhateTrains** [comment]
My initial guess is that the bug occurs when the mapped CK3 title is already owned in vanilla.
