### ISSUE TITLE
Error " SQL logic error table playsets has no column "

### ISSUE THREAD

**Issue by MasuRii** [ParadoxGameConverters/ImperatorToCK3#1214]
**Logs**
[log.txt](https://github.com/ParadoxGameConverters/ImperatorToCK3/files/10776351/log.txt)

**Version:**
 - OS: Windows 10 Pro : 21H2 : 19044.1766
 - ImperatorToCK3 6.2.17

**Comment by IhateTrains** [comment]
What's the version of your Imperator launcher?

**Comment by MasuRii** [comment]
It says v2.2023.2, but I solve the error by deleting both

- launcher-v2.sqlite
- launcher-v2_openbeta.sqlite

It doesn't show error anymore
