### ISSUE TITLE
Culture splitting

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/ImperatorToCK3#122]
Approximate regions to split some culture groups: 
![image](https://user-images.githubusercontent.com/24550392/107758425-23666f80-6d27-11eb-9e96-9fdf79aa9dc9.png)

Cultures in italics are not in vanilla CK3. I:R-CK3 converter does not support regional mappings.

Source → /↓ Region | Germanic culture group | Italic culture group (except Etruscan) | Punic culture| Hellenistic culture group
-- | -- | -- | -- | --
A | _iweric_ | _breathanach_ | _ythalonim_ | _eblanic_
B | scots | _transadrianic_ | _ythalonim_ | _scotinous_
C | anglo-saxon | _brythenig_ | _ualonuth_ | _prettanian_
D | norse | _läßin_ | _sicorathi_ | _hyperborean_
E | french | norman | _symacom_ | _velgese_
F | french | occitan | _ysthyalm_ | _metalpesian_
G | Vanilla German (bavarian, dutch, franconian, saxon, swabian) | _läßin_ | _sicorathi_ | _prinelbite_
H | _pémiš_ | _wenedyk_ | _sythchy_ | _metalbite_
I | lombard | cisalpine | _ynnocho_ | _prinalpesian_
J | _ostrogothic_ | _pannonian_ | _mlachthi_ | _delmatic_
K | _pémiš_ | vlach | _inythmum_ | _macedonian_ (the Greek one, not the Slavic one)
L | _varangian_ | _euxinian_ | _gadolite_ | _anatolian_
M | _aryan_ | _bazramani_ | _bythlimmoth_ | _susite_
N | _gegenjiddisch_ | _judajca_ | _sidonian_ | _azotite_
O | _wostiyasite_ | _salinatorian_ | _carthaginian_ | _carchidonian_
P | lombard | italian | _taliaite_ | _italiote_
Q | lombard | sicilian | _lacanite_ | _hyperochian_
R | _mikligarðrish_ | _xliponian_ | _epicrateian_ | greek
S | lombard | sardinian | _pmpese_ | _xarthic_
T | visigothic | catalan | _ythbynuthi_ | _varquelonic_
U | visigothic | aragonese | _ythbynuthi_ | _varquelonic_
V | visigothic | asturleonese | _ychibarku_ | _vaskician_
W | suebi | galician | _ychibarku_ | _vaskician_
X | visigothic | castilian | _liphocaneth_ | _vaitic_
Y | visigothic | portuguese | _mysehi_ | _lousitanian_

Special cases:
- Italic cultures (as well as Etruscan) held by the Roman Empire are always converted to Roman
- Hebrew becomes ashkenazi in regions D, G, H; sephardi in regions T through Y; khazar in region L; _shuadit_ in region F; _zarphatic_ in region E.

Sent through public Wi-Fi.

**Comment by IhateTrains** [comment]
> I:R-CK3 converter does not support regional mappings.

This is no longer the case.

**Comment by IhateTrains** [comment]
What is gegenjiddisch based on?
