### ISSUE TITLE
Logic in DeterminePrimarySourceProvince

### ISSUE THREAD

**Issue by Illgeo** [ParadoxGameConverters/ImperatorToCK3#1544]
The logic in 
https://github.com/ParadoxGameConverters/ImperatorToCK3/blob/7aca11db96484a0d0594ecedf5d3570af94b56ca/ImperatorToCK3/CK3/Provinces/ProvinceCollection.cs#L172 
doesn't seem to make sense to me. Shouldn't this line add to share. or at least take the max of current share and current province dev? Because right now it seems as if it just overwrites and thus basically takes one random (last in collection) province per owner to compare?

**Comment by IhateTrains** [comment]
I think you're right, it should add to the share instead of replacing it after every province. Thanks for noticing!
I will write some tests to make sure and push a fix.

**Comment by IhateTrains** [comment]
@Illgeo could you check if it works for you better in new release 8.0.13?

**Comment by Illgeo** [comment]
Oh, I didn't notice it in any specific game, I was reading through code recreationally :-D

**Comment by IhateTrains** [comment]
Still, thanks for finding the mistake!
