### ISSUE TITLE
Conversion of wealth

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/ImperatorToCK3#164]
Characters in I:R saves have a wealth entry, which can be output as an add_gold entry.

**Comment by IhateTrains** [comment]
We need to determine how valuable the Imperator currency is.

**Comment by RaduM84** [comment]
Recommendation : 1-to-1 conversion of wealth between Imperator and CK3.

**Comment by RaduM84** [comment]
> We need to determine how valuable the Imperator currency is.

Buildings in I:R and CK3 cost roughly the same, 100 currency units give or take depending on building. A 1-to-1 is broadly correct.
