### ISSUE TITLE
Remove vanilla CK3 de jure kingdoms and empires

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#184]
Unless it causes errors.

**Comment by IhateTrains** [comment]
> Couldn't we just rename them with I:R appropriate names? E.g. Francia could be renamed Gallia

It doesn't always make sense, some de jure kingdom shapes are very specific, e.g. Venice.
![image](https://user-images.githubusercontent.com/29546927/114080638-e85a6580-98ab-11eb-9a29-c5a929cd2e82.png)
I see little point in keeping the vanilla setup, even renamed, if it's mostly based on events that took place in OTL between the periods covered by I:R and CK3. Instead, we can either rely on de jure drift, or help it a bit.
@Zemurin does CK3ToEU4 rely on vanilla CK3 de jure in a way that could be broken by this change?

> Otherwise, the I:R export area would have a halved de jure hierarchy and would only ever have I:R countries up until the 15th century

I don't mean to remove de jure for I:R area, but the whole map.

**Comment by IohannesIohannium** [comment]
De jure drift would solve things if there were Kingdoms and Empires already. An area that is contended by multiple kingdoms and empires would end up having no de jure Empire.

About Venice, the whole existance of it makes no sense without the Hunnic and Ostrogothic invasions of the 6th century, so we can simply put it into Italy. We could create a new de jure setup based on I:R provinces for some start, better than nothing.

**Comment by IohannesIohannium** [comment]
I got a more interesting idea: we export I:R areas as de jure duchies and I:R regions as de jure kingdoms. And we can forget about de jure empires entirely.

**Comment by Zemurin** [comment]
> 
> 
> > Couldn't we just rename them with I:R appropriate names? E.g. Francia could be renamed Gallia
> 
> It doesn't always make sense, some de jure kingdom shapes are very specific and unprobable in alternative timeline, e.g. Venice.
> ![image](https://user-images.githubusercontent.com/29546927/114080638-e85a6580-98ab-11eb-9a29-c5a929cd2e82.png)
> I see little point in keeping the vanilla setup, even renamed, if it's mostly based on events that took place in OTL between the periods covered by I:R and CK3. Instead, we can either rely on de jure drift, or help it a bit.
> @Zemurin does CK3ToEU4 rely on CK3 de jure in a way that could be broken by this change?
> 
> > Otherwise, the I:R export area would have a halved de jure hierarchy and would only ever have I:R countries up until the 15th century
> 
> We can also do this for the whole map.

Ck3ToEU4 largely doesn't care about dejure setup, as long as it's consistent. Title names for custom titles come from the savegame itself, so feel free to do whatever you need, and if it breaks something I'll fix it on my end (just report it with a test setup).
