### ISSUE TITLE
central_italy_region and the screams of the converter

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/ImperatorToCK3#186]
For some absurd reason, the converter does not recognize central_italy_region as an I:R region and screams metric tons of lines about how it can't map X culture/religion based on an unknown region "central_italy_region"

The result is the converted lagging for a good 5 minutes while screaming all those lines

**Comment by IohannesIohannium** [comment]
[log.txt](https://github.com/ParadoxGameConverters/ImperatorToCK3/files/6281256/log.txt)

**Comment by IhateTrains** [comment]
You're using an old version, before the fix for RegionMapper.
