### ISSUE TITLE
Character converted to unexpected religion

### ISSUE THREAD

**Issue by MatthewForrester** [ParadoxGameConverters/ImperatorToCK3#1898]
**System information**
Converter: 10.5
Imperator: 2.0.4 Open Beta
CK3: 1.12.4 Scythe
OS: Linux

**Steps to reproduce**

1. Check _Imperator_ is using the Open Beta, with the _Invictus_ and _Timeline Extended_ mods available
2. Unzip this file and place it in your Imperator saves directory: [809.12.24-Pritania.rome.zip](https://github.com/ParadoxGameConverters/ImperatorToCK3/files/15052975/809.12.24-Pritania.rome.zip)
3. Use the Converter to convert the save to CK3
4. Add the resulting mod to CK3 and create a playset containing it
5. Open the save and start a new game using the character in the bookmark, Orgetorix II ab Romulus

**Expected result**

The player character (`139135`) has the same religion as the rest of his dynasty and the territories that he rules, as was the case in the I:R save.

**Actual result**

The player character's religion is Druidic. In the converter mod's `/bookmarks/bookmarks/00_bookmarks.txt` and `/history/characters/IRToCK3_fromImperator.txt` files the player character's religion is `religion=celtic_pagan`.

But the religion of his demesne, and the other characters in his dynasty, is Brythonic Druidism (`briton_paganism`).

![ConvertedReligionError](https://github.com/ParadoxGameConverters/ImperatorToCK3/assets/38819845/17fe2ebc-7bc0-49f7-8107-5b6c738c00c9)

FYI there are lands in other parts of the map where `faith = celtic_pagan`.

**Comment by IhateTrains** [comment]
Hi, first of all thanks for a detailed report! It's a rare occurrence :)

For some reason, according to the save your ruler character is located in a sea province:
```
province=5710
```
which belongs to `mare_britannicum_area`. The converter didn't expect that.

I've tweaked the converter to use a land province (country's capital, father's location or mother's location) instead in such case.
The ruler is now correctly converted as Brython-Druidic.

New version will be up in around 10 minutes.
