### ISSUE TITLE
Monarchy Rome converts to republic?

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#233]
> So I have a problem with the converter it keeps converting Rome as a republic despite it being a monarchy

used version: 1.2.3

**Comment by Xavantex** [comment]
I am experiencing the same problem. Anything the team wants to investigate it?

**Comment by IhateTrains** [comment]
> I am experiencing the same problem. Anything the team wants to investigate it?

Please upload your save.

**Comment by Xavantex** [comment]
Certainly. I got no mods, it was ironman save, only a few years after end date
[450.10.1 - Rome.zip](https://github.com/ParadoxGameConverters/ImperatorToCK3/files/7697593/450.10.1.-.Rome.zip)
.

**Comment by IhateTrains** [comment]
@Xavantex thanks for the save, I was able to investigate. Please check if release 2.12.2 fixes the problem for you, it did for me.
