### ISSUE TITLE
Adjust starting date to match the save's date

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#234]

**Comment by TinWiz** [comment]
CK3 tech starts in 476, should that be the earliest possible conversion date?

**Comment by IhateTrains** [comment]
> CK3 tech starts in 476, should that be the earliest possible conversion date?

Sorry for not responding. I think the earliest possible conversion date should not be that late. Many people convert around 1st century, so this would cause a big gap.
