### ISSUE TITLE
Cultures to add and revise

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/ImperatorToCK3#252]
(Waiting for the CK3 new patch to drop before working on it)

- [x] Galatian (from modded I:R _galatian_) / issue #239 
- [x] Hunnic (no I:R source)
- [x] Proto-Baltic and Proto-Slavic (from I:R _aestian_)
- [x] Various Iron Age Italian cultures: Oscan from _osco_umbrian_ and _umbrian_, Samnite from _samnite_, Venetic from _venetic_, Ligustic from _ligurian_, Messapic from _lucanian_ and _bruttian_, Sardonian from _sardonian_, Siculian from _siculian_
- [x] Adnanite and Qahtanite, to represent pre-Islamic Arabs.

Mappings to correct:
- [x] Wusun should be mapped to Pecheneg instead of Sogdian. Pecheneg-Wusun identity is a historical hypothesis, but surely more reliable than just shoving them into Sogdian
- [x] Shule to Saka. Quoth Wikipedia, _Much like the neighboring people of the Kingdom of Khotan, people of [the Shule Kingdom] spoke Saka, one of the Eastern Iranian languages._
- [x] Yuezhi to Bactrian. According to the spoken language, which is not Greek.

From forum:
- [ ] Mede 1-1 mapping? [https://forum.paradoxplaza.com/forum/threads/imperator-to-ck3-release-thread.1415172/post-27769127](https://forum.paradoxplaza.com/forum/threads/imperator-to-ck3-release-thread.1415172/post-27769127) - not implemented; the Mede-Kurd mapping is convenient because it gives us a source for CK3 Kurdish culture and doesn't require adding a Median culture to blankMod
- [x] Elamite 1-1 mapping? [https://forum.paradoxplaza.com/forum/threads/imperator-to-ck3-release-thread.1415172/post-27769127](https://forum.paradoxplaza.com/forum/threads/imperator-to-ck3-release-thread.1415172/post-27769127)
- [x] Magadhi to Bengali [https://forum.paradoxplaza.com/forum/threads/imperator-to-ck3-release-thread.1415172/post-27763343](https://forum.paradoxplaza.com/forum/threads/imperator-to-ck3-release-thread.1415172/post-27763343)

**Comment by DrDudelsack** [comment]
There are mappings and support for many of those old Iron Age cultures in the EU IV and Victoria II converters created for I:R to CK II. If the same internal I:R to CK II names are used (like old_ligurian for the Ligurians), they should be painless to add into I:R to CK III

**Comment by IhateTrains** [comment]
> * Wusun should be mapped to Pecheneg instead of Sogdian. Pecheneg-Wusun identity is a historical hypothesis, but surely more reliable than just shoving them into Sogdian

Could you point to a source? Wikipedia article on Wusun doesn't mention Pechenegs

**Comment by IohannesIohannium** [comment]
> > * Wusun should be mapped to Pecheneg instead of Sogdian. Pecheneg-Wusun identity is a historical hypothesis, but surely more reliable than just shoving them into Sogdian
> 
> Could you point to a source? Wikipedia article on Wusun doesn't mention Pechenegs

I could only get a sentence from https://it.wikipedia.org/wiki/Peceneghi :

> Secondo un'altra teoria, i peceneghi proverrebbero dal popolo wusun, menzionato dai cinesi nei primi secoli della nostra epoca in quella stessa regione.

Translation: _According to another theory, the Pechenegs would come from the Wusun people mentioned by the Chinese in the first centuries of common era in that same area._
