### ISSUE TITLE
Spouses are doubled for dead Imperator characters

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#312]
![image](https://user-images.githubusercontent.com/29546927/133317951-28aa7b7c-d27d-4ffc-998b-f723d3228f3d.png)
![image](https://user-images.githubusercontent.com/29546927/133317973-1a7416b9-a4d6-4940-8949-b8a0aff33d06.png)
![image](https://user-images.githubusercontent.com/29546927/133318018-ce7a1efb-9805-4544-b1c0-edb330220b89.png)

**Comment by IohannesIohannium** [comment]
Are you perhaps outputting the marriage entry both for husband and wife? If yes, just output it for the husband and it should be solved.

**Comment by IhateTrains** [comment]
> Are you perhaps outputting the marriage entry both for husband and wife? If yes, just output it for the husband and it should be solved.

That's the approach I'll take. I wonder if it doesn't break matriarchal polygamy, though.
