### ISSUE TITLE
Investigate how a CK3 mod introduced BC dates

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#392]
https://steamcommunity.com/sharedfiles/filedetails/?id=2642459836

Won't use the solution if it's too hacky, though.

**Comment by IohannesIohannium** [comment]
Seems to be through the use of customizable locs and "set_immortal_age" to get the correct age. Would work good only on already dead characters, would look absurd with living ones

**Comment by IohannesIohannium** [comment]
Char history file:
![image](https://user-images.githubusercontent.com/24550392/141788440-b0d70578-ebdf-4e23-ad39-58d1a9e8d6e2.png)
Custom locs file:
![image](https://user-images.githubusercontent.com/24550392/141788512-c484ba70-77f6-47af-ab35-32b3aa80ba13.png)
Custom triggers file:
![image](https://user-images.githubusercontent.com/24550392/141788594-eea5b437-d845-42be-8776-65c90e5ed56a.png)

**Comment by IhateTrains** [comment]
Thanks for investigating, looks like something the converter could generate for every BC ruler. French codenames make it a bit harder to understand, though :<

**Comment by IhateTrains** [comment]
With CK3 now not breaking on BC dates, this is no longer needed.
