### ISSUE TITLE
Family name form

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/ImperatorToCK3#430]
Family names should prefer conversion from the _male form_ (e.g. Publius) rather than the _plural form_ (Publii), mimicking vanilla CK3 (using Stroganov, not Stroganovy). Forms in I:R are male.female.plural.adjectival (Stroganov/Stroganova/Stroganovy/Stroganovian)
The best approach would be to inherit all forms, so that a man called _Marcus Publius_ would have a daughter named _Marca Publia_ rather than _Marca Publius_, but alas CK3 game engine can't do that (_Ivan Stroganov_ and his daughter _Marya Stroganov_[sic!])

**Comment by IohannesIohannium** [comment]
Closed: I:R records only the third form in the save and building a parser solely for this is of little use

**Comment by IhateTrains** [comment]
Such parser wouldn't be too difficult to write.
