### ISSUE TITLE
Actually support Imperator mods

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#48]
The converter only reads CK3 stuff from CK3 game path. It should also read from mods' folders.

EDIT: The new goal is to support Imperator mods.

- [x] read localization from mods
- [x] read regions from mods
- [x] read genes from mods

**Comment by IohannesIohannium** [comment]
Converters should consider source mods and not target mods, as these latter could alter map, traits and other core things so radically that a truly-working converter would be unfeasible.

**Comment by IhateTrains** [comment]
Doesn't EU4ToVic2 support HPM?

**Comment by Zemurin** [comment]
No, but cetvrtak pit a pr up that would create a hpm hybrid. Otherwise not a chance.
