### ISSUE TITLE
Write a Python script to autolocalize frontend options for other languages with Google Translate

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#51]

**Comment by IohannesIohannium** [comment]
No need to. Just default to English until a suitable translation is added.

**Comment by IhateTrains** [comment]
Zemurin suggested adding at least auto-translated loc and Idhrendur is interested in the script too, so it's still relevant.

**Comment by IhateTrains** [comment]
Created this when I still cared enough about other languages but now I don't. Users gotta learn English 🤷🏼‍♂️
