### ISSUE TITLE
Post-mapping religion setup tweaks

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#52]
- [ ]  If Islam didn't spawn, make Muslim provinces in Arabia Arabic Pagan, make Muslim provinces in West Africa Berber Pagan, make Muslim provinces in South Africa Waaqi
- [x]  If Coptic religion didn't emerge, make Coptic provinces Kushite or Egyptian Pagan
- [x]  If Christianity/Orthodoxy didn't emerge, make Orthodox provinces Hellenic
- [x]  Make that one Tengri county around Romania Balkanic Pagan, or preferably copy a neighboring county's religion

**Comment by IhateTrains** [comment]
The Islam tweak should wait until religion and province mappings are up-to-date.

**Comment by IohannesIohannium** [comment]
Muslim Somalians are a result of historically scripted Muslim characters. If start date is moved to 150 AD, the problem is automatically solved.
