### ISSUE TITLE
Religious head landed titles have no holders?

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#541]

**Comment by IhateTrains** [comment]
> here is a save converted in AD 476. There is a Roman Pope and Ecumenical Patriarch, and an Armenian Katholikos, but neither a Coptic Pope nor a Patriarch of the East. https://www.dropbox.com/s/jh2pp040k74jgpu/v0.9.3_1229.9.11%20-%20Empire%20romain_CONVERT.zip?dl=0

**Comment by IhateTrains** [comment]
> One more from a different timeline (the above two are from the same), converted in AD 497 and all Christian HoFs are there. So I don't know if it's the date or something else. https://www.dropbox.com/s/rls0c1qr5lmaour/1250.6.28%20-%20Empire%20romain%20d%27Orient_CONVERT.zip?dl=0

**Comment by TinWiz** [comment]
Any way I can help with this?

**Comment by IhateTrains** [comment]
Vanilla CK3 `d_coptic_papacy` has no holder between 444 and 490, so not a bug per se. I might add a game start on_action to create a holder for the title if it doesn't have one, but I'd be better if someone with better modding skills did that.

**Comment by IhateTrains** [comment]
For `d_patriarchate_in_the_east`, I think the problem is that some of its holders, including the 476 AD one, are set through `holder_ignore_head_of_faith_requirement` history command instead of `holder`, and the converter doesn't currently support that,
