### ISSUE TITLE
Convert dynasties

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#55]

**Comment by IohannesIohannium** [comment]
For characters, a line `dynasty = family_Something` should be used
Then, a common/dynasties/imp_dynasties.txt should get generated having lines like this:
```
family_Something = {
	name = "dynn_Something"
	culture = "[the culture of the main character of that family, using "roman" as an arbitrary fallback]"
}
```
And finally localisation/[language]/imp_dynasty_l_[language].yml, one for each language, starting with the obvious l_[language] line and then having a ` dynn_Something:0 "Something"` line for each of them.

Of course, I used Something as an example and the actual family name from I:R should be used.
We don't need to worry about coats of arms, but a regular scheme like this allows us to possibly create some in blankMod

**Comment by IhateTrains** [comment]
> culture = "[the culture of the main character of that family, using "roman" as an arbitrary fallback]"

I think that there should be no need for this fallback. If a family is not dead, it should always be able to take culture from the head character. If it doesn't, the converter should die.

**Comment by IohannesIohannium** [comment]
Maybe it's a borked save or the family is converted with entirely dead characters. Having a fallback is there *only* in case stuff goes weird, for which we do this 1. output some default-fallback 2. add a log line saying something went wrong
