### ISSUE TITLE
Assign at least 2 traditons to each of our cultures

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#581]

**Comment by IohannesIohannium** [comment]
- Gaulish cultures should have tradition_polygamous (Some pre-Christian [Celtic pagans](https://en.wikipedia.org/wiki/Celtic_paganism) were known to practice polygamy, although the [Celtic peoples](https://en.wikipedia.org/wiki/Celtic_peoples) wavered between it, [monogamy](https://en.wikipedia.org/wiki/Monogamy) and [polyandry](https://en.wikipedia.org/wiki/Polyandry) depending on the time period and the area.[[50]](https://en.wikipedia.org/wiki/Polygamy#cite_note-Markale1986-51) In some areas this continued even after Christianization began, for instance the [Brehon Laws](https://en.wikipedia.org/wiki/Brehon_Laws) of [Gaelic Ireland](https://en.wikipedia.org/wiki/Gaelic_Ireland) explicitly allowed for polygamy,[[51]](https://en.wikipedia.org/wiki/Polygamy#cite_note-52)[[52]](https://en.wikipedia.org/wiki/Polygamy#cite_note-53) especially amongst the noble class.[[53]](https://en.wikipedia.org/wiki/Polygamy#cite_note-54) Some modern Celtic pagan religions accept the practice of polygamy to varying degrees,[[54]](https://en.wikipedia.org/wiki/Polygamy#cite_note-55) though how widespread the practice is within these religions is unknown.) and tradition_sacred_groves
- Hellenistic and Macedonian should have tradition_concubines (In [Ancient Greece](https://en.wikipedia.org/wiki/Ancient_Greece) the practice of keeping a concubine ([Ancient Greek](https://en.wikipedia.org/wiki/Ancient_Greek_language): παλλακίς pallakís) was common among the upper classes, and they were for the most part women who were slaves or foreigners, but occasional free born based on family arrangements (typically from poor families).[[48]](https://en.wikipedia.org/wiki/Concubinage#cite_note-BlundellBlundell1995-49))
- Phoenicians and Carthaginians should have tradition_seafaring
