### ISSUE TITLE
Set martial custom for all our cultures

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#584]

**Comment by IohannesIohannium** [comment]
I would use martial_custom_male_only in most cultures. Exceptions that should use egalitarian: Brythonic (referencing Boudicca), Gaulish group, Illyrian (but not Albanian), Scythian (referencing Tomyris).

Considering https://imperator.paradoxwikis.com/Military_traditions:
* Barbaro-Celtic tradition: tradition_hit_and_run
* Barbaro-Britannic tradition: tradition_horse_breeder
* Greek tradition: tradition_swords_for_hire
* Indian tradition: tradition_formation_fighting
* Italic tradition: tradition_only_the_strong
* Levantine tradition: tradition_warriors_of_the_dry
* North African tradition: tradition_warriors_by_merit
* Persian tradition: tradition_formation_fighting
