### ISSUE TITLE
Move `common/culture/culture_names` to `common/culture/name_equivalency`

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#590]

**Comment by mayuri-dhote** [comment]
Hi @IhateTrains I want to solve this issue. Don't we have to just rename this file? As i cannot see the other location where you said to move.

**Comment by IhateTrains** [comment]
> Hi @IhateTrains I want to solve this issue. Don't we have to just rename this file? As i cannot see the other location where you said to move.

Indeed, we just need to move `ImperatorToCK3/Data_Files/blankMod/output/common/culture/culture_names/IR_names.txt` file to ImperatorToCK3/Data_Files/blankMod/output/common/culture/name_equivalency`

**Comment by mayuri-dhote** [comment]
Hi @IhateTrains I have generated PR for the same. Kindly review and merge.

**Comment by IhateTrains** [comment]
Thanks, merged!
