### ISSUE TITLE
CK3 initializing takes a really long time

### ISSUE THREAD

**Issue by TinWiz** [ParadoxGameConverters/ImperatorToCK3#677]
I've noticed since the recent update it takes a very long time for a CK3 game converted using the Simple I:R Timeline Extender mod to initialize. 

Dropbox link to .zip for the save:
https://www.dropbox.com/s/6c31zwo6bc2ax9m/TEv098_1229.9.5%20-%20Seleukid%20Empire_CONVERT.zip1.zip?dl=0

 and mod files for most recent timeline extender:
https://www.dropbox.com/s/tyzxvx9atnpeitx/IR_TE%20v0.9.8.zip?dl=0

[I'm not able to attach zip files here, it gives the error, "is not included in the list".]

**Comment by IhateTrains** [comment]
Does it take noticeably longer than from a vanilla Imperator save?

**Comment by TinWiz** [comment]
I'll test that.

**Comment by TinWiz** [comment]
Vanilla also takes a long time, although I could not get the save to 476 because it crashed (created too many countries). 

https://www.dropbox.com/s/7exbkughmqg0l0z/1140.1.1%20-%20Persian%20Empire_387.1.1_CONVERT.zip?dl=0

**Comment by IhateTrains** [comment]
> and mod files for most recent timeline extender:
> https://www.dropbox.com/s/tyzxvx9atnpeitx/IR_TE%20v0.9.8.zip?dl=0

I can't use it without the .mod file.

**Comment by IhateTrains** [comment]
The long loading is caused by the game logging a lot of character history date errors. I have an idea for solving this by normalizing BC character dates to range 0.1.1 - 0.12.31.
Release 3.2.0 should slightly improve the load time because of character purging.

**Comment by IhateTrains** [comment]
The long loading is caused by the game logging a lot of character history date errors. I have an idea for solving this by normalizing BC character dates to range 0.1.1 - 0.12.31.
Release 3.2.0 should slightly improve the load time because of character purging.

**Comment by TinWiz** [comment]
I noticed a slight load time improvement, from about 15 minutes to about 10 minutes.

**Comment by TinWiz** [comment]
I timed this with the current version of the converter and it took 6 minutes.
