### ISSUE TITLE
[Linux] (Mint 20.04) wxwidgets libwx_gtk3u_unofficial_core-3.1.so.5 and libwx_baseu_unofficial-3.1.so.5

### ISSUE THREAD

**Issue by Quinnux** [ParadoxGameConverters/ImperatorToCK3#694]
Hi, I'm unable to run the Converter on Linux Mint 20.04 due to missing non/default dependencies.

As far as I can tell, it looks like the issues are with the "unofficial" Codelite wxWidgets and the newer version of libstdc++ (or the other way of looking at it is that the issue is with a 20.04 LTS :) )

A few outputs here:

./ConverterFrontend
```
./ConverterFrontend: error while loading shared libraries: libwx_gtk3u_unofficial_core-3.1.so.5: cannot open shared object file: No such file or directory
```

ldd ConverterFrontend
```
./ConverterFrontend: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./ConverterFrontend)
	[...]
	libwx_gtk3u_unofficial_core-3.1.so.5 => not found
	libwx_baseu_unofficial-3.1.so.5 => not found
	[...]
```
Everything else is present.

**libwx**
By default, these appear to go up to version libwx_gtk3u_core-3.0.so.0.4.0
The newer/unofficial version seems to be available separately from a ppa, [Codelite wxWidgets ](https://docs.codelite.org/wxWidgets/repo316/#ubuntu-and-debian)

**GLIBCXX**

strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
```
GLIBCXX_3.4
GLIBCXX_3.4.1
[...]
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
I think this is just an issue of LTS releases, I'd expect this to sort itself out in any imminent 22.04 Ubuntu/Mint releases. Otherwise it looks like it's kind of backported here, in gcc-11:
[ppa:ubuntu-toolchain-r/test](https://launchpad.net/%7Eubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=focal)

Anyway, not sure whether this is an "I should change my system" or a "you should change your build, or list the dependencies in a readme" - but hopefully useful reference if anyone else sees the same issue.

I think the GLIBCXX one will not be an issue with newer releases, but the libwx ones appear to be only available from the website PPA. The equivalent dependencies without "unofficial" in them should be included in newer releases. 
[Using unofficial to avoid name clash](https://docs.codelite.org/downloads/download/#setup)

I've not tried retesting with the PPAs in place yet, but it looks like it has a good chance of working.

Can it be recompiled with older libraries, or should I try and update through these PPAs?

**Comment by IhateTrains** [comment]
Hi, in a couple of days I should have an MVP version of a new frontend (based on C# and AvaloniaUI instead of C++ and wxWidgets), which should solve the required library issues: https://github.com/ParadoxGameConverters/Fronter.NET/tree/develop

In the meantime, if you want to help us with building the current frontend, please see what needs to be changed in this script to make it compatible with your OS version:
https://github.com/ParadoxGameConverters/Fronter/blob/8d6c76bf625c385c93af87e43dab7f59dd88b86c/.github/actions/build_frontend/entrypoint.sh#L14

**Comment by Quinnux** [comment]
Hi, thanks for the quick response, and thanks for your time and help with this.

Having a look at the linked file, it looks like it is taking the newer/alternate versions from the same sources I linked in the first post - so I guess one option is simply to put in the readme that it requires those versions - or I'm not sure if you can bundle the dependencies with the file (like in an appimage/flatpak/snap etc)?

Note I mistakenly referred to current Linux Mint as 20.04 - whereas it is actually "Linux Mint 20.03, based on Ubuntu 20.04", just to be confusing.

Anyway, I had a look through the previous Ubuntus that are still currently supported, which are:

18.04 "Bionic" LTS until april 2023
20.04 "Focal" LTS until april 2025 (+ Current Mint Version)
21.10 "Impish" until july 2022 (+ Current POP!_OS Version)
22.04 "Jammy" LTS (just released a couple of days ago, after I posted that message)

Then looked at which versions of those dependencies were in the repos/installed in system by default:

### **GCC stuff** (causing error in GLIBCXX)

**Ubuntu 20.04 LTS** (and **Linux Mint 20.03**)
gcc-10 g++-10

**Ubuntu 21.10, Pop!_OS 21.10, Ubuntu 22.04**
gcc-11 g++-11
gcc-10 g++-10

### **For the WXWidgets3.0 stuff**
Default repo system libs for all versions (from **18.04**, including **22.04**, **Mint**, **POP!_OS** etc)

libwxbase3.0-0v5
libwxbase3.0-dev
libwxgtk3.0-gtk3-0v5
libwxgtk3.0-gtk3-dev
wx3.0-headers
wx-common

The libcurl bit mentioned I think is fine for any version.

So... this may be a little beyond my knowledge/skill level, but if there's no specific requirement in the program for the "3.1 unnofficial" and "GLIBCXX_3.4.29" versions, then something like the following might do the trick:

```
else
    sudo apt install libcurl4-openssl-dev
    sudo apt install gcc-10 g++-10
    sudo apt install libwxbase3.0-0v5 libwxbase3.0-dev libwxgtk3.0-gtk3-0v5 libwxgtk3.0-gtk3-dev wx3.0-headers wx-common
    # Link gcc-10 and g++-10 to their standard commands
    sudo ln -s /usr/bin/gcc-10 /usr/local/bin/gcc
    sudo ln -s /usr/bin/g++-10 /usr/local/bin/g++
    # Export CC and CXX to tell cmake which compiler to use
    export CC=/usr/bin/gcc-10
    export CXX=/usr/bin/g++-10
    # Check versions of gcc, g++ and cmake
    gcc -v && g++ -v && cmake --version

    rm -rf Release/
    cd Fronter
    ./build_linux.sh
    mv Release ../
  fi

```
I've basically removed the repo commands and switched the versions to the slightly older ones. I recommend to check it through properly though, as there's likely typo/formatting errors.

Hope that's of some use! Let me know if there's anything else that wants looking at or testing.

Many thanks again for your time and work.

**Comment by IhateTrains** [comment]
> **Ubuntu 20.04 LTS** (and **Linux Mint 20.03**) gcc-10 g++-10
> 
> **Ubuntu 21.10, Pop!_OS 21.10, Ubuntu 22.04** gcc-11 g++-11 gcc-10 g++-10

g++-11 is definitely required because of C++20 features we use.

> Default repo system libs for all versions (from 18.04, including 22.04, Mint, POP!_OS etc)
> 
> libwxbase3.0-0v5
> libwxbase3.0-dev
> libwxgtk3.0-gtk3-0v5
> libwxgtk3.0-gtk3-dev
> wx3.0-headers
> wx-common

@Zemurin is it possible for Fronter to target wxWidgets 3.0?

**Comment by IhateTrains** [comment]
@Quinnux here's a dev build with a new shiny frontend, could you test if it works for you and successfully converts a save?
https://mega.nz/file/KB9miCzL#iOxNH1AI_WHK9kjT_3e1CoWRY4_TUXvEmHaebE51lwg

**Comment by Quinnux** [comment]
Hi, the short version is "It worked!" thank you so much for your help with this - looks and works great. My save game is a little too early to convert/test fully, but I had it loaded up in CK3, correct family names, characters, locations, cultures etc and ran it for a few in-game weeks.

A couple of things I had to adjust:

1) The converter wouldn't detect my CK3 and Imperator binaries (called simply "imperator" and "ck3" with no filename ending - I had to copy & rename them to "imperator.exe" and "ck3.exe" for it to detect them.

2) I needed to set the executable bit on ConverterFrontend (which I was expecting to do anyway) and ImperatorToCK3/ImperatorToCK3Converter (which I didn't expect to do).

Again, thanks so much for your help with getting this running, and for your work on the converters in the first place :)

**Comment by IhateTrains** [comment]
> The converter wouldn't detect my CK3 and Imperator binaries (called simply "imperator" and "ck3" with no filename ending - I had to copy & rename them to "imperator.exe" and "ck3.exe" for it to detect them.

solved with #711

**Comment by IhateTrains** [comment]
> I needed to set the executable bit on ConverterFrontend (which I was expecting to do anyway) and ImperatorToCK3/ImperatorToCK3Converter (which I didn't expect to do).

Please check release [3.5.0](https://github.com/ParadoxGameConverters/ImperatorToCK3/releases/tag/3.5.0) to see if the issue is resolved.

**Comment by Quinnux** [comment]
Brilliant, thank you! I've just tested it - everything runs, works, converts perfectly. Original issue is entirely solved :)
