### ISSUE TITLE
Purge vanilla characters that don't hold any title

### ISSUE THREAD

**Issue by IhateTrains** [ParadoxGameConverters/ImperatorToCK3#73]

**Comment by IohannesIohannium** [comment]
The converter should have a configurable file, called purgeCultures.txt, where it lists the cultures for which we should remove CK3 characters.
If in purgeCultures.txt we have the line ABC, the converter will output /history/characters/ABC.txt as a blank file and thus erase all CK3 vanilla characters with ABC culture.

**Comment by IhateTrains** [comment]
> The converter should have a configurable file, called purgeCultures.txt, where it lists the cultures for which we should remove CK3 characters.
> If in purgeCultures.txt we have the line ABC, the converter will output /history/characters/ABC.txt as a blank file and thus erase all CK3 vanilla characters with ABC culture.

Is this really needed? If no characters of a culture hold titles after importing Imperator countries, it will effectively be purged.

**Comment by IohannesIohannium** [comment]
They would still exist as random courtiers wandering around, which can be
interesting in case of Catholics and Muslims roaming off a world where
Christ had yet to be born

**Comment by IhateTrains** [comment]
> They would still exist as random courtiers wandering around

No, the point of this issue is that they would be purged.

**Comment by IohannesIohannium** [comment]
Then we would risk deleting spouses and children of everyone outside the I:R map

**Comment by IhateTrains** [comment]
> Then we would risk deleting spouses and children of everyone outside the I:R map

This isn't really a problem, I think CK3 generates family members for childless/spouseless rulers. Also, that's what Zemurin advised.
![image](https://user-images.githubusercontent.com/29546927/114283401-db737880-9a49-11eb-969f-08e84ac3df23.png)

**Comment by IohannesIohannium** [comment]
150 AD conversion would mean no need to purge any character, as almost no vanilla character is even defined to begin with

**Comment by IhateTrains** [comment]
150 AD must be optional, so it doesn't solve this.
