### ISSUE TITLE
Conversion of government offices

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/ImperatorToCK3#89]
We'll eventually consider converting them. We just need to remember to add *867.1.1 = { set_employer = ABC }*, with ABC being their ruler, in the character's history file.

Office mappings (CK3 || I:R first choice, I:R other choice, etc.)
- Court Chaplain || Augur, High Priest, Royal Tutor, Court Philosopher, Wise One
- Chancellor || Censor, Chancellor, Arbitrator, Elder
- Steward || Magistrate, Steward
- Marshal || Tribune of the Soldiers, Tribune of the Treasury, Marshal, Master of the Guard, Warchief, Bodyguard
- Spymaster || Tribune of the People

Furthermore, we have CK3 Court Physician, who is not a *councillor* but a *courtier*, and maps to I:R Physician and I:R Apothecary

**Comment by IhateTrains** [comment]
Council positions are given in character history in the following way:
```
	1176.4.20 = {
		employer = 204500
		give_council_position = councillor_marshal
	}
```

Respective council position IDs:
- councillor_court_chaplain
- councillor_chancellor
- councillor_steward
- councillor_marshal
- councillor_marshal

**Comment by IhateTrains** [comment]
Some more conversion possibilities as of CK3 1.12:

Royal Tutor -> Court Tutor court position
Bodyguard -> Bodyguard court position
