### ISSUE TITLE
Conversion of governors

### ISSUE THREAD

**Issue by IohannesIohannium** [ParadoxGameConverters/ImperatorToCK3#90]
Governors should map to vassals.

This, however, also requires a regionMap.txt mapping file to explain what title a governor gets.

**Comment by IhateTrains** [comment]
We can also autogenerate the titles like I did for tag->title conversion.

**Comment by IohannesIohannium** [comment]
Yes, but I would suggest adding a regionMap.txt for some cases.
Syntax: `link = { imp = lusitania_region ck3 = k_portugal rank = e }`
Rank refers to the rank of the *overlord*. A governor will always be one rank lower (except for generated independent duchies, in which case governors would *not* be converted)

**Comment by IohannesIohannium** [comment]
[governorMappings.txt](https://github.com/ParadoxGameConverters/ImperatorToCK3/files/5545475/governorMappings.txt)

**Comment by IohannesIohannium** [comment]
Coats of arms of governors could be generated like this:

```
k_GOVERNOR_[ABC]_[XYZ] = {
    sub = {
        parent = "e_IMPTOCK3_[ABC]"
        instance = { offset = { 0.0 0.0 } scale = { 0.5 0.5 }  } # top left
        instance = { offset = { 0.5 0.5 } scale = { 0.5 0.5 }  } # bottom right
    }
    sub = {
        parent = "[XYZ]"  # defined elsewhere
        instance = { offset = { 0.5 0.0 } scale = { 0.5 0.5 }  } # top right
        instance = { offset = { 0.0 0.5 } scale = { 0.5 0.5 }  } # bottom left
    }
}
```

Where ABC is the country in I:R and XYZ the region. All regions will be defined.

**Comment by IohannesIohannium** [comment]
Localisation for governors could be generated as "[ABC_adj] [XYZ]", where ABC is the I:R country, XYZ the region; e.g. a governorate in Cisalpine Gaul by the Romans would be generated as the Kingdom of "Roman Cisalpine Gaul".

Titles for governors would be generated as "k_GOVERNOR_[ABC]_[XYZ]". Governors for countries that are lower tier than Empires should be discarded. The governor of the capital region of the country will also be discarded. In all other instances, a governor will gain the generated governorate title and all counties that are found to be within it.

The governorate title will always have de_jure_drift_disabled = yes, can_be_named_after_dynasty = no, can_create = { always = no }

The governorate title will be defined as de jure part of the country it is part of.
E.g.:
```
e_IMPTOCK3_PRY = {
    ...
    k_GOVERNOR_PRY_central_italy_region = {
        ...
    }
}
```
The governorate title's history should look like this (recycling example from above):
```
k_GOVERNOR_PRY_central_italy_region = {
    769.1.1 = {
        holder = imperator123
        liege = "e_IMPTOCK3_PRY"
        government = feudal_government
        succession_laws = { high_partition_succession_law }
    }
}
```

high_partition_succession_law will mean that the successors of the governor will never hold two governorates at the same time.

**Comment by IhateTrains** [comment]
> Governors for countries that are lower tier than Empires should be discarded.

Don't you mean kingdoms?

**Comment by IohannesIohannium** [comment]
Yes, my bad

**Comment by IhateTrains** [comment]
Stuff left to do:
- [ ] generate governorship colors with country color serving as base https://discord.com/channels/612683871112396800/692883287336681592/889701266035453984
- [ ] convert governors under duchies to county holders
- if region has only 1 governorship:
    - [ ] don't add country adjective to name (example: Persis instead of Persian Persis)
- if region has multiple governorship:
    - [ ] if an area is fully controlled, use area name for governorship name
    - [ ] most developed controlled territory

**Comment by IhateTrains** [comment]
> The governorate title will always have de_jure_drift_disabled = yes, can_be_named_after_dynasty = no, can_create = { always = no }

Should it apply to vanilla titles from your mappings?

**Comment by IohannesIohannium** [comment]
No

**Comment by IhateTrains** [comment]
> The "can't be created etc." part should be pasted only on regions that generate multiple governorates
> Persian Persis would get it, Arachosia wouldn't, Ireland wouldn't, Carthaginian Portugal would

**Comment by IhateTrains** [comment]
> > The "can't be created etc." part should be pasted only on regions that generate multiple governorates
> > Persian Persis would get it, Arachosia wouldn't, Ireland wouldn't, Carthaginian Portugal would

Governorships being named <country adjective> <region name> like Carthaginian Portugal should be extremely rare now (they're supposed to use area and province names instead), so I think the limitations to title creation and de jure drift are no longer needed.

**Comment by IhateTrains** [comment]
> Coats of arms of governors could be generated like this:
> 
> ```
> k_GOVERNOR_[ABC]_[XYZ] = {
>     sub = {
>         parent = "e_IMPTOCK3_[ABC]"
>         instance = { offset = { 0.0 0.0 } scale = { 0.5 0.5 }  } # top left
>         instance = { offset = { 0.5 0.5 } scale = { 0.5 0.5 }  } # bottom right
>     }
>     sub = {
>         parent = "[XYZ]"  # defined elsewhere
>         instance = { offset = { 0.5 0.0 } scale = { 0.5 0.5 }  } # top right
>         instance = { offset = { 0.0 0.5 } scale = { 0.5 0.5 }  } # bottom left
>     }
> }
> ```
> 
> Where ABC is the country in I:R and XYZ the region. All regions will be defined.

@IohannesIohannium if you want to proceed with this, please create a file with CoA definitions for regions. But I think it should be limited to only the regions that we know what should be used as flag for. I imagine it's a few at most. For the remaining governorships CK3 can just generate CoAs like it does now.
