### ISSUE TITLE
Will generated cultures get traditions in the later updates?

### ISSUE THREAD

**Issue by nah34** [ParadoxGameConverters/ImperatorToCK3#988]
Hello, I've used the converter a few times, and I wanted to know if the converted cultures in ck3 will get more traditions.

The vanilla ck3 cultures have an average of 3 traditions at the start of the game (if you look at the ck3 wiki).
On the other hand the newly generated cultures in ck3 have about 1~2 traditions, which I think, could affect depth and gameplay.
For example, the Macedonian culture when converted into ck3, only has 1 tradition even though they usually become one of the most populous cultures (due to the diadochis ruling over vast territories) at the end of the imperator rome run. That goes for many other tribal Germanic or North African nations. This is a great difference compared to Roman or Greek cultures which has up to 5 traditions.

So, if possible, **could the team add traditions for the generated cultures in ck3, for flavor purposes?** It would add a great depth if every culture gets adequate characteristics.

To some it may seem like a trivial issue, and I guess I have no say even if it's not doable, but I sure hope it would boost the mod's completeness. Take your time, and best wishes for every team member.

**Comment by IhateTrains** [comment]
@nah34 Hi, it can be done. The problem is determining which traditions a culture should have.
You can help. Could you post a list of cultures with which traditions they should have in your opinion, with reasoning?

For example: Carthaginian culture should have Maritime Mercantilism tradition because Carthaginians were highly successful traders who sailed the Mediterranean with their goods

**Comment by nah34** [comment]
Oh, that is quite delightful news! I'd happily participate in sharing ideas in that sense. :)


**Scythian**
Since all other vanilla ck3 Iranian cultures have 4 traditions, I found it suitable to give Iranian cultures such as Scythian, Sarmatian, or Bactrian **extra 2 traditions** each with the existing two ones. 

**Scythian** culture should have **Martial Admiration** tradition because "… He also states that "Ares," the god of war, was the only god to whom the Scythians dedicated statues, altars or temples. Tumuli were erected to him in every Scythian district, and both animal sacrifices and human sacrifices were performed in honor of him. At least one shrine to "Ares" has been discovered by archaeologists. (from the Scythians wikipedia page"

**Scythian** culture should also have **Horse Lords** tradition because Scythians and Sarmatians were well-known for their horse archers.
One thing to keep in mind is that Horse Lords tradition is enabled only for Mongolic or Turkic heritages in vanilla ck3. **So you may need to mod the condition to unlock it for Iranian Heritages also.**


**Sarmatian**
**Sarmatian** culture should have **Prolific Hunters** tradition both because nomads such as these were usually hunter-gathers, and some scholars theorize the name Sarmatia itself comes from the word meaning "hunter". (… Harold Walter Bailey derived the name Saurumatā, composed of … a derivation of the Iranian root *sar-, … which was a cognate of the Old Indic base tsar- (त्सर्) from which were derived the terms tsarati- (त्सरति) and tsaru- (त्सरु), meaning "hunter." (from the Sarmatians wikipedia page))

Sarmatian culture should also have **Horse Lords** tradition because Scythians and Sarmatians were well-known for their horse archers.


By the way, I honestly think the martial custom of Scythian and Sarmatian culture should be opposite, **Scythian being 'Martial: Men Only'** and **Sarmatian being 'Martial: Equal'**, because "Unlike the other Scythic peoples such as the Sarmatians, where women were allowed to go hunting, ride horses, learn archery and fight with spears just like the men, the society of the Scythians proper was patriarchal and Scythian women possessed little freedom. (from the Scythians wikipedia page)"

**Comment by nah34** [comment]
For now I've only requested ideas for only two of the dozens of converted cultures from the mod, and I think we can add many more. I for example am from East Asia and might have an insight of Asian cultures (whereas there should be mod developers who are far better than me for knowing western cultures such as Celtics). 
Do you have any list of all of the cultures newly created by the converter? Any document or sheet file might be nice, and I would like to tackle culture traditions starting with ones east of Caucasus!

**Comment by IhateTrains** [comment]
@nah34 thanks for the suggestions for Scythian and Sarmatian! All should be implemented now, also added you to the credits list.

> For now I've only requested ideas for only two of the dozens of converted cultures from the mod, and I think we can add many more. I for example am from East Asia and might have an insight of Asian cultures (whereas there should be mod developers who are far better than me for knowing western cultures such as Celtics). Do you have any list of all of the cultures newly created by the converter? Any document or sheet file might be nice, and I would like to tackle culture traditions starting with ones east of Caucasus!

There is currently no complete list of converter cultures, but I will prepare such a thing. Will let you know when it's ready, shouldn't take too long.

**Comment by IhateTrains** [comment]
@nah34 inside this zip you'll find a table with all cultures added/modified by the converter. It contains traditions given to every culture.
[generated_docs.zip](https://github.com/ParadoxGameConverters/ImperatorToCK3/files/9742300/generated_docs.zip)

**Comment by nah34** [comment]
> @nah34 inside this zip you'll find a table with all cultures added/modified by the converter. It contains traditions given to every culture. Some of the cultures like Transadrianic, Wenedyk, Breathanach etc. are fictional and probably will be removed at some point, so I wouldn't spend time on them.

Thank you for the well-documented file! I'll try to search for Chaldean, East Slavic, Iranian and Mongolic heritages first. These 4 heritages make up 8 cultures, so I'll keep posting it here probably one by one so you wouldn't have to bother answering each of them. Thank you again for the quick reply!

**Comment by nah34** [comment]
**Aramaic**
With the existing 2 traditions, Aramaic culture should have these **2 extra ones**.

**Aramaic** culture should have **Refined Poetry** tradition because Aramaic language was used as a common language during the reign of Babylonian and Achaemenid Empire. They were revered for being excellent writers. (The Persians considered this Chaldean societal class to be masters of reading and writing, and especially versed in all forms of incantation, sorcery, witchcraft, and the magical arts. They spoke of astrologists and astronomers as Chaldeans, and it is used with this specific meaning in the Book of Daniel (Dan. i. 4, ii. 2 et seq.) and by classical writers, such as Strabo. (from the wikipedia Chaldea page))

**Aramaic** culture should have **Culture Blending** tradition because Chaldean cultures such as Aramaic were often blended with other cultures. (The original Chaldean tribe had long ago became Akkadianized, adopting Akkadian culture, religion, language and customs, _blending into_ the majority native population, and eventually wholly disappearing as a distinct race of people, as had been the case with other preceding migrant peoples, such as the Amorites, Kassites, Suteans and Arameans of Babylonia. (from the Chaldea wikipedia page) / The Arameans who lived outside their homelands apparently _followed the traditions of the country where they settled._ The King of Damascus, for instance, employed Phoenician sculptors and ivory-carvers. In Tell Halaf-Guzana, the palace of Kapara, an Aramean ruler (9th century BCE), was decorated with orthostates and with statues that display a mixture of Mesopotamian, Hittite, and Hurrian influences. (from the Arameans wikipedia page)).

Also, I personally think **Aramaic** culture should have **Dryland Dwellers instead of Hill Dwellers**, since Aramaic culture is mainly located at where all the Syrian desert is.

**Comment by IhateTrains** [comment]
Thanks for the suggestions, Aramaic changes are implemented.
Would you like to join our converters discord where we discuss most of the development of ImperatorToCK3 and other converters? If yes, let me know your Steam/Paradox forum username and I'll send you an invitation :)

**Comment by nah34** [comment]
Oh, I'd be glad to join the discord! Though I have no knowledge of programming or coding, I'd be happy to discuss ideas in that regard. 
My steam ID is **pavodeus97**. If you can't find it, my steam profile address is https://steamcommunity.com/profiles/76561198307444045/
